require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  CacheRootDirectory: tmp/rubocop

##############################################################################
# Bundler
##############################################################################

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false
